site_name: GRAPE

nav:
    - Home: 'index.md'
    - User Guide:
        - Overview: 'UserGuide.md'
        - GUI & Command Line Tool: 'Gui&CommandLineTool.md'
        - Datasets: 'Datasets.md'
        - Input Data: 'InputData.md'
        - Runs & Outputs: 'Runs&Outputs.md'
    - Schema: 'Schema.md'
    - About: 'About.md'

theme:
    name: material
    logo: Icon/GrapeIcon512.png
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: amber
          accent: green
          toggle:
            icon: material/weather-night
            name: Dark Mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: amber
          accent: green
          toggle:
            icon: material/weather-sunny
            name: Light Mode

    features:
        - navigation.expand
        - navigation.indexes
        - navigation.instant
        - navigation.sections
        - navigation.tabs
        - navigation.top
        - navigation.tracking
        
        - search.highlight
        - search.share
        - search.suggest

copyright: Copyright &copy; 2022 Goncalo Soares Roque
docs_dir: docs
site_dir: site

markdown_extensions:
    # Python Markdown
    - tables
    - toc:
        title: On this page
        toc_depth: 3
    
    # Python Markdown Extensions
    - pymdownx.highlight
    - pymdownx.superfences