site_name: GRAPE

nav:
    - Home: index.md
    - Application:
        - Application/index.md
        - Command Line Tool: Application/CommandLineTool.md
    - IO:
        - IO/index.md
        - Conversion Tables: IO/ConversionTables.md
        - CSV Files: IO/CSVFiles.md
        - ANP Folder: IO/ANPFolder.md
        - Geopackage Files: IO/GeopackageFiles.md
    - Schema:
        - Schema/index.md
    - About: 'About.md'

theme:
    name: material
    logo: Icon/GrapeIcon512.png
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: green
          accent: amber
          toggle:
            icon: material/weather-night
            name: Dark Mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: green
          accent: amber
          toggle:
            icon: material/weather-sunny
            name: Light Mode

    features:
        - navigation.expand
        - navigation.indexes
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - navigation.tracking
        
        - search.highlight
        - search.share
        - search.suggest

copyright: Copyright &copy; 2023 Gon<span>&#231;</span>alo Soares Roque
docs_dir: docs
site_dir: site

markdown_extensions:
    - admonition
    - attr_list

    # Python Markdown
    - tables
    - toc:
        title: On this page
        toc_depth: 3
    
    # Python Markdown Extensions
    - pymdownx.highlight
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg